# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Headers123!
    ports:
      - 127.0.0.1:27017:127.0.0.1:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:127.0.0.1:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Viva-Jaen-NP
      ME_CONFIG_MONGODB_URL: 'mongodb://root:Headers123!@mongo:27017/'
