# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: <db user>
      MONGO_INITDB_ROOT_PASSWORD: <db pass>
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: <express user>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <express pass>
      ME_CONFIG_MONGODB_URL: mongodb://<db user>:<db pass>@mongo:27017/      
